### ISSUE TITLE
Serving HTTP(S) Webpages

### ISSUE THREAD

**Issue by frink** [meta-word/RingSocket#4]
Generally, I like the architecture developed here. However, I feel that it would be much more useful if you also handled HTTP protocol since most websocket apps serve the frontend through HTTP and it seems pointless to run a second server just for that purpose. Even if this was merely a static server it would be wildly helpful.

**Comment by wbudd** [comment]
Thank you for opening RingSocket's first issue!

I understand that it would be convenient if RingSocket were to serve HTTP(S) content, especially during full-stack development; but to be honest, it's not going to happen. It's good to have this issue as a future Q&A reference though, so I'll try to articulate why I strongly feel that having such functionality included would be a poor idea.

Just stating the obvious here, but neither WebSocket nor HTTP are protocols that are easy to implement *well*. However, between the two, the difficulties they pose are of an almost entirely different nature—many of HTTP's quirks stemming from "organic growth" over the past three decades.

As you know, there are already a great number of excellent solutions for serving HTTP(S), but even if someone were to create a pull request for RingSocket containing a full-blown HTTP server implementation, I would probably still refuse it. Aside from being in agreement with the Unix philosophy that "*programs should do one thing and do it well*", my foremost concern is security.

Any HTTP-handling code is bound to be vulnerability-sensitive. WebSocket-handling code is similarly high-stakes. The way I see it, implementing them both in the same monolithic program would create a recklessly large attack surface to maintain and worry about. One "tiny" flaw on either side of the protocol divide is all it would take to rain down disaster on the whole system. To keep said attack surface as small as possible, RingSocket only does the bare minimum required to handle the HTTP upgrade handshake and implement the WebSocket core protocol as stipulated by RFC 6455.

Besides, I see a certain beauty in RingSocket *not* handling HTTP(S). One of the things I like about WebSocket is how it allows websites to limit their usage of HTTP(S) to serving static content only—the one task the HTTP protocol was actually designed to do well—with all the caching benefits that may entail, while deferring all handling of dynamic content to full-duplex WebSocket tunnels.

For example, for publicly hosted websites I use scripted `aws-cli` functionality to send all my front-end stuff off to Amazon S3 buckets as static content, while handling their dynamic needs through RingSocket installed locally on a home server—different protocol, different domain, different IP address, different port, different machine, different city; different solution.

**Comment by frink** [comment]
I'll leave the issue open so it's easy for people to find your stance on the issue...
